### ISSUE TITLE
It work only for administrator and not work for other players. 0.4.14 stable.

### ISSUE THREAD

**Issue by amadin** [taikedz/everamzah-mechanisms#1]
It work only for administrator and not work for other players. 0.4.14 stable.

**Comment by taikedz** [comment]
Works for me. Can you give more details please?

Test with a player and a wooden door, list player's privs, distance of doors from plate

**Comment by amadin** [comment]
Privs for amdinistrator:
![- 23 11 2016 - 09 15 02](https://cloud.githubusercontent.com/assets/13412191/20553543/2336eb86-b15e-11e6-9aeb-123871748853.png)

Privs for player:

![- 23 11 2016 - 09 15 52](https://cloud.githubusercontent.com/assets/13412191/20553564/3f3ea9fe-b15e-11e6-82ff-d588748d15a7.png)

Wooden door and wooden plate:

![- 23 11 2016 - 09 16 58](https://cloud.githubusercontent.com/assets/13412191/20553579/502ccb2e-b15e-11e6-8d97-3f1586a4a096.png)

**Comment by taikedz** [comment]
Odd - that should work. There is nothing in the code that calls to depend on any privs or player.

Have you tried without any other mods present? The pressure plate only detects whether a player is on it, it then uses the default doors mechanisms to open/close the door. If that behaviour itself has been overridden by another mod, the pressure plates would be affected.

**Comment by amadin** [comment]
Oh i undestand, i use Protected door from protector-redo mod.

**Comment by amadin** [comment]
Maybe you know how to make it work with doors from protector-redo mod?

**Comment by taikedz** [comment]
Probably need to make a pull request to Protector to have it register the doors as `groups = {door=1, ...}`

**Comment by amadin** [comment]
I tried but server crash:

2016-11-23 21:02:32: ERROR[Main]: ServerError: Lua: Runtime error from mod 'mechanisms' in callback node_on_timer(): ...e/ra/Minetest-stable-0.4/bin/../mods/mechanisms/init.lua:17: attempt to index local 'door' (a nil value)
2016-11-23 21:02:32: ERROR[Main]: stack traceback:
2016-11-23 21:02:32: ERROR[Main]: 	...e/ra/Minetest-stable-0.4/bin/../mods/mechanisms/init.lua:17: in function 'door_toggle'
2016-11-23 21:02:32: ERROR[Main]: 	...e/ra/Minetest-stable-0.4/bin/../mods/mechanisms/init.lua:43: in function <...e/ra/Minetest-stable-0.4/bin/../mods/mechanisms/init.lua:33>

**Comment by taikedz** [comment]
OK I see the problem

We use default doors' mechanisms to get a valid door:

https://github.com/taikedz/everamzah-mechanisms/blob/master/init.lua#L11

Which is a reference to

https://github.com/minetest/minetest_game/blob/master/mods/doors/init.lua#L10

Protector doesn't register doors with the `doors` mod, so when we try to get the door info, the function actually returns nil.

Two potential solutions:

* re-write protector so that the doors are properly registered (which means other mods such as mesecons, etc, can use the protector doors)
* re-write `mechanisms` to cater for custom doors, and re-write every time a new mod makes a custom door

I am not in favour of writing workarounds for bespoke doors. If a mod adds custom doors, it should register against the `doors` mod.

So the first solution is preferred. Please raise an issue against `protector` to ask to register the doors through the `doors` mod.
